329: Retain floating point precision when converting floats
unitsofmeasurement/indriya pull request #331
Opened 2021-02-16 17:21 UTC by daniel-shuy

Fixes #329

`DefaultNumberSystem` uses `BigDecimal` to preserve floating point precision for double arithmetic, but `Float#doubleValue()` does not preserve floating point precision, leading to precision loss for float arithmetic.

2021-02-16 17:28 UTC, keilw commented
The cast of `(float)number` looks a little ugly, I thought `Number` still has a `floatValue()` method, or was that dropped recently?
@daniel-shuy you are not a JCP member at least on an Associate level, are you?
Because as mentioned in the [Contribution-Guide](https://github.com/unitsofmeasurement/unit-api/wiki/Contribution-Guide) the RI unlike most other modules requires a JCP agreement.

2021-02-16 17:32 UTC, daniel-shuy commented
> The cast of (float)number looks a little ugly, I thought Number still has a floatValue() method, or was that dropped recently?

I agree, I originally wanted to use `Number#floatValue()` as well as it is safer, but used `(float)number` because the existing code was using `(double)number`. I'll gladly change it if you wish.

> @daniel-shuy you are not a JCP member at least on an Associate level, are you?
Because as mentioned in the Contribution-Guide the RI unlike most other modules requires a JCP agreement.

Ah, sorry, wasn't aware. I'll apply for a membership.

2021-02-16 17:43 UTC, keilw requested changes
Aside from the cast which could be improved a bit, please @daniel-shuy join the JCP as Associate member if you can. Ask @andi-huber who also is an Associate member if you need help. Will keep this open for now, it does not sound ultra-critical for the upcoming 2.1.2 release of Indriya but happy to merge once the JCP membership is sorted (hoping there are no merge conflicts;-)

2021-02-16 20:32 UTC, daniel-shuy commented
I've applied the suggestions and added tests

2021-04-17 23:23 UTC, keilw commented
@daniel-shuy How is your JCP membership going?

2021-04-19 05:04 UTC, daniel-shuy commented
@keilw I discussed with my employer and they wanted to join the JCP as an organization, so I was waiting for it to be approved before I can register under my employer. The organization membership has been approved, now I just need to register as an individual and request member association.

Sorry, I've been putting it off because there hasn't been any activity in the discussion since (#332).

2021-04-19 09:57 UTC, daniel-shuy commented
@keilw If I am joining the JCP under an organization, do I have to ask my employer to apply for membership to the JSR or can I do that individually?

2021-04-19 10:13 UTC, keilw commented
@daniel-shuy No, Associate Membership works without asking your employer, see https://jcp.org/en/participation/membership the two bottom options. There is currently no cost for either, but if your employer is not interested to get involved then Associate sounds best and we have plenty of Associate members who contribute the same or sometimes even more than other Full Members.

2021-04-19 10:49 UTC, daniel-shuy commented
@keilw my employer wants to get involved, as I am contributing to libraries that are widely used by the company. I've joined the JCP under my employer, and I've submitted a nomination to join the JSR, thanks!

2021-04-19 12:43 UTC, andi-huber commented
Please understand, I don't see a bug with the current implementation.

By all means, please, if you find an issue other than that, which is subject to the discussion (#332), of course I'll have a closer look.

2021-04-19 14:10 UTC, daniel-shuy commented
@andi-huber yes, we've established its not a bug, but a potential improvement to make it less confusing for users of the library.

If not, I propose adding a note to warn users of the library that converting floats between different units can result in additional "noise" (while it is technically more accurate, the end user may not know that, and to them it is noise).

2021-04-19 15:37 UTC, keilw commented
@daniel-shuy Float is usually less precise see [https://stackoverflow.com/questions/27598078](https://stackoverflow.com/questions/27598078/float-and-double-datatype-in-java#:~:text=Double%20takes%20more%20space%20but,less%20space%20but%20less%20precise.&text=According%20to%20the%20IEEE%20standards,use%20of%20double%20data%20type.)

2021-04-19 18:25 UTC, andi-huber reviewed
This PR was intended under the premise of cutting off float's at their decimal representation accuracy limit. If that were our goal, I'd consider this contribution at its most parts valid.

But unfortunately the suggested changes break with the current scheme that is to properly extend floats to double before converting them to any higher precision container.

2021-04-19 18:25 UTC, andi-huber commented on src/main/java/tech/units/indriya/function/RationalNumber.java
> +	public static RationalNumber of(float number) {
As mentioned above, breaks the general scheme of first extending floats to double before converting them to BigDecimal or Rational.

2021-04-19 18:25 UTC, andi-huber commented on src/main/java/tech/units/indriya/function/DefaultNumberSystem.java
> +            return new BigDecimal(wide.toString())
At this point wide is potentially a float, so don't break consistency.

2021-04-19 18:25 UTC, andi-huber commented on src/main/java/tech/units/indriya/function/DefaultNumberSystem.java
> +            return new BigDecimal(wide.toString())
dito: consistency

2021-04-19 18:25 UTC, andi-huber commented on src/main/java/tech/units/indriya/function/DefaultNumberSystem.java
> +        return new BigDecimal(wide.toString())
At this point wide is potentially a float, so don't break consistency.

2021-04-19 18:25 UTC, andi-huber commented on src/main/java/tech/units/indriya/function/DefaultNumberSystem.java
> +                return ((BigDecimal) wide).multiply(new BigDecimal(narrow.toString()), Calculus.MATH_CONTEXT);
dito: consistency

2021-04-19 18:25 UTC, andi-huber commented on src/main/java/tech/units/indriya/function/DefaultNumberSystem.java
> +                return wide.floatValue() * narrow.floatValue();
I'd rather not do that, as by extension to double we can guarantee the float value multiplication not to overflow. Its a corner case granted, but why risk that?

2021-04-19 18:25 UTC, andi-huber commented on src/main/java/tech/units/indriya/function/DefaultNumberSystem.java
> +            return new BigDecimal(wide.toString())
At this point wide is potentially a float, so don't break consistency.

2021-04-19 18:25 UTC, andi-huber commented on src/main/java/tech/units/indriya/function/DefaultNumberSystem.java
> +            return new BigDecimal(wide.toString())
dito: consistency

2021-04-19 18:25 UTC, andi-huber commented on src/main/java/tech/units/indriya/function/DefaultNumberSystem.java
> +        return new BigDecimal(wide.toString())
At this point wide is potentially a float, so don't break consistency.

2021-04-19 18:25 UTC, andi-huber commented on src/main/java/tech/units/indriya/function/DefaultNumberSystem.java
> +                return ((BigDecimal) wide).compareTo(new BigDecimal(narrow.toString()));
dito: consistency

2021-04-19 18:34 UTC, andi-huber commented
If there is enough momentum, we surely can think of providing different `NumberSystem` implementations optimized for different use-cases, so users have options. But I'd rather have the default one, not optimized for usability or performance but rather for fail-safety.

2021-04-19 19:21 UTC, andi-huber commented
Hi @daniel-shuy - on a personal note:  

These technical discussions are sometimes time consuming, exhausting and have a tendency toward frustration, especially if precious spare time is going into it. In that context, I want to be clear, that you are very welcome as a new contributor.

2021-04-20 12:26 UTC, daniel-shuy commented
@andi-huber thanks for taking the time to review the PR. After the discussion, I'm actually in agreement to not change the current behavior, due to the corner cases. I was actually trying to push for adding a note to warn users of the behavior, but as @keilw pointed out above, if the user of the library wants accuracy, then they shouldn't be using `float` in the first place.

I'm happy to drop this issue, but I'd still be glad to join the JSR, as I have other improvements I would like to contribute back.

2021-04-20 12:53 UTC, keilw commented
@daniel-shuy Thanks a lot for the update and understanding. We're happy to accept your invitation to the JSR and EG as a contributor anticipating further activity or improvement. For the number systems @andi-huber mentioned, please also see this discusison item #328. It is not fully fleshed out with comments to actually vote on, but the idea is to use this new GH feature and offer 2 or 3 candidates like Commons Number or Decimal4J and implement either one or multiple plugins to replace the built-in `RationalNumber` where a different `NumberSystem` is required.

2021-04-20 12:53 UTC, closed without merging